name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    uses: TappNetwork/workflows/.github/workflows/phpstan.yml@main
    with:
      php_version: '8.3'
      phpstan_config: 'phpstan.neon.dist'
      timeout_minutes: 5
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
